version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./containAdmin
    command: /bin/sh -c "/wait && /opt/app/containAdmin/manage.py migrate --noinput  && /opt/app/containAdmin/manage.py runserver 0.0.0.0:8000"
    environment:
      WAIT_HOSTS: db:5432
      WAIT_HOSTS_TIMEOUT: 60
    volumes:
      - static_volume:/opt/app/containAdmin/static
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/opt/app/containAdmin/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:
